### ISSUE TITLE
MasterKeyChangeRec appears 2 time in Metadata fields list

### ISSUE THREAD

**Issue by TheZ3ro** [keepassxreboot/keepassxc-specs#1]
The same field `MasterKeyChangeRec` appears 2 times in the Metadata fields list with 2 different meanings.
I think there is a Typo and the second one should be `MasterKeyChangeForce`

----

Page3 [line 215](https://github.com/keepassxreboot/keepassxc-specs/blob/master/kdbx-xml/rfc.txt#L215)

```
   <MasterKeyChangeRec>  _INTEGER_ indicating the number of days after
      which the password manager SHOULD recommend changing the
      database's master key (-1 means 'never')
```

Page4 [line 229](https://github.com/keepassxreboot/keepassxc-specs/blob/master/kdbx-xml/rfc.txt#L229)
```
   <MasterKeyChangeRec>  _INTEGER_ indicating the number of days after
      which the password manager SHOULD force changing the database's
master key (-1 means 'never')
```

**Comment by phoerious** [comment]
Gotya. The latter is supposed to be MasterKeyChangeForce.
