### ISSUE TITLE
Add HeaderHash information in section 2.3.2 of kdbx-xml rfc

### ISSUE THREAD

**Issue by TheZ3ro** [keepassxreboot/keepassxc-specs#2]
Since the kdbx-xml rfc is describing both KDBX3.1 and KDBX4, should be nice adding the HeaderHash field to the Meta data list.

This field is used in KDBX3.1 but not in version 4, also KeePass website recommends to not store it/remove it from a KDBX4 file.

Citing KeePass website
> In KDBX 4, the HeaderHash element in the XML part is now obsolete and is not stored anymore.

**Comment by phoerious** [comment]
Will do.

**Comment by TheZ3ro** [comment]
PS: The RFC is very well written :wink:

**Comment by phoerious** [comment]
Still a lot of room for improvement, but at least a lot better than everything else out there.
